version: '2'

services:

  web:
    build: .
    command: npm start
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    ports:
      - "3001:8080"
    depends_on:
      # - mongo
      - psql
    # networks:
    #   frontend:
    #     ipv4_address: 172.20.0.1
    # environment:
    #   # WAIT_HOSTS: mongo:27017, pgdb:5432
    #   POSTGRES_URL: postgres://172.20.0.2:5432
    #   MONGO_URL: mongodb://172.20.0.3:27017
    env_file: .docker.env
    # smae level of the docker compose

  psql:
    image: postgres
    # restart: always
    # linux constring and user and password and database name
    volumes:
      - ./dataP:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      # POSTGRES_USER: docker
    # networks:
    #   frontend:
    #     ipv4_address: 172.20.0.2
    
  # mongo:
  #   image: mongo
  #   volumes:
  #     - ./dataM:/data/db:rw
  #   ports:
  #     - "27017:27017"
    # networks:
    #   frontend:
    #     ipv4_address: 172.20.0.3

# networks:
#   frontend:
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16
#         # - subnet: 172.20.0.0/24